let items = [
  {
    productName: "item정렬 방식 flex vs grid",
    category: 'flex-grid',
    url: "basic/flex_grid_item_layout_compare.html",
  },
  {
    productName: "CSS로 목록 스타일을 개선하는 2가지 방법",
    category: "basic",
    url: "basic/2ways_improve_list_styling.html",
  },
  {
    productName: "div 요소의 내용 인쇄",
    category: "basic",
    url: "basic/print_contents_div_element.html",
  },
  {
    productName: "grid를 이용한 덜 절대적인 위치 잡기",
    category: 'flex-grid',
    url: "basic/grid/absolute_positioning_modern.html",
  },
  {
    productName: "css focus-visible(:focus 대신 사용)",
    category: 'mouse-effect',
    url: "basic/css_focus-visible(instead-focus).html",
  },
  {
    productName: "css all 속성에 대해서",
    category: "basic",
    url: "basic/css_all.html",
  },
  {
    productName: "반응형 전체 화면 배경",
    category: 'background-border',
    url: "basic/responsive_full-screen_background.html",
  },
  {
    productName: "논리적 속성을 사용하여 더 나은 CSS 작성",
    category: "basic",
    url: "basic/write_better_css_logical_properties.html",
  },
  {
    productName: "투명한 PNG 이미지 그림자 적용",
    category: 'image',
    category2: 'background-border',
    url: "basic/shadows_transparent_PNG.html",
  },
  {
    productName: "프로젝트에서 사용할 수 있는 flexbox 디자인 패턴",
    category: 'flex-grid',
    url: "basic/flex/flexbox_design_patterns_projects.html",
  },
  {
    productName: "css auto-margin 정렬",
    category: 'flex-grid',
    category2: 'layout',
    url: "basic/auto_margin.html",
  },
  {
    productName: "그리드로 쉽게 콘텐츠 겹침",
    category: 'flex-grid',
    url: "basic/grid/easily_overlap_content.html",
  },
  {
    productName: "배경 비디오를 만드는 방법",
    category: 'background-border',
    url: "basic/how_to_create_background_video.html",
  },
  {
    productName: "background-blend-mode에 대해서",
    category: 'background-border',
    url: "basic/css_background_blend_mode.html",
  },
  {
    productName: "css calc() 에 대해서",
    category: "basic",
    url: "basic/css_calc().html",
  },
  {
    productName: "css object-fit을 사용하여 이미지를 제어하는 방법",
    category: 'image',
    url: "basic/css_object-fit.html",
  },
  {
    productName: "미디어 쿼리가 없는 반응형 CSS 그리드!",
    category: 'flex-grid',
    category: 'layout',
    url: "basic/grid/responsive_no_media_queries.html",
  },
  {
    productName: "배경반복 값 space에 대해서",
    category: 'background-border',
    url: "basic/background_repeat_space.html",
    linkType: 'outlink',
  },
  {
    productName: "다른 색상의 CSS 이중 테두리",
    category: 'background-border',
    url: "basic/double_border_width_diffrent_colors.html",
  },
  {
    productName: "영리한 고정 바닥글 기법",
    category: 'layout',
    url: "basic/sticky_footer_technique.html",
  },
  {
    productName: "그림자 그라디언트",
    category: 'background-border',
    url: "basic/grdient_drop_shadow.html",
  },
  {
    productName: "줄무늬 배경",
    category: 'background-border',
    url: "basic/stiped_background_pattern.html",
  },
  {
    productName: "도트 배경",
    category: 'background-border',
    url: "basic/dot_background_pattern.html",
  },
  {
    productName: "css touch-action 한눈에보기",
    category: 'mouse-effect',
    url: "basic/touch-action.html",
  },
  {
    productName: "css 가상요소 선택자 - marker",
    category: 'basic',
    url: "basic/css가상요소_marker.html",
  },
  {
    productName: "mix-blend-mode 사용 예시 (isolation)",
    category: 'background-border',
    url: "basic/css_mix-blend-mode_사용.html",
  },
  {
    productName: "inset을 이용한 full 레이아웃",
    category: 'layout',
    url: "basic/css_inset_layout.html",
  },
  {
    productName: "input에 관하여",
    category: 'form',
    category2: 'basic',
    url: "basic/input.html",
  },
  {
    productName: "유동적인 타이포그래피 css함수 - clamp()",
    category: 'text-effect',
    url: "basic/유동적인_타이포그래피_clamp().html",
  },
  {
    productName: "반전 그림자 표현 reflected text",
    category: 'text-effect',
    url: "basic/reflected_text.html",
  },
  {
    productName: "skeleton screen",
    category: 'icon-loading',
    url: "basic/skeleton_screen.html",
  },
  {
    productName: "skeleton screen 여러개",
    category: 'icon-loading',
    url: "basic/skeleton_screen2.html",
  },
  {
    productName: "flex margin-top 이용한 footer고정",
    category: 'layout',
    url: "basic/footer_flex(margin).html",
  },
  {
    productName: "와인샵 컨셉_반응형 슬라이더(GREENSOCK)",
    category: 'slide',
    url: "slide/wine_shop_concept_responsive_slider.html",
  },
  {
    productName: "응답성이 뛰어난 최소 포트폴리오 웹 사이트",
    category: 'slide',
    url: "slide/minimal_portfolio/index.html",
  },
  {
    productName: "고급스러운 반응형 슬라이드 slick.js",
    category: 'slide',
    url: "slide/responsive_slider_slickjs/index.html",
  },
  {
    productName: "gsap를 이용한 세로로 부드럽게 슬라이드",
    category: 'slide',
    url: "slide/vertical_content_slider.html",
  },
  {
    productName: "수직 카드 슬라이딩 애니메이션(only css)",
    category: 'slide',
    url: "slide/vertical_card_sliding_animation.html",
  },
  {
    productName: "계속 반복되는 한줄이미지 배너(only css)",
    category: 'slide',
    url: "slide/infinite_autoplay_carousel(only-css).html",
  },
  {
    productName: "멀티플 슬라이드 순수 자바스크립트",
    category: 'slide',
    url: "slide/multiple_slideshow_loop.html",
  },
  {
    productName: "이미지 반사 효과 3D 슬라이더",
    category: 'slide',
    url: "slide/3D_image_slider_reflection_Materialize.html",
    linkType: 'outlink',
  },
  {
    productName: "Glide.js를 사용한 놀라운 효과의 이미지 슬라이드",
    category: 'slide',
    url: "slide/glide/index.html",
  },
  {
    productName: "Javascript를 사용 Mousemove에서 이미지 회전 제어",
    category: 'slide',
    url: "slide/control_image_rotation_mousemove.html",
  },
  {
    productName: "circular rotating reflection",
    category: 'slide',
    url: "slide/css_circular_rotating_slider_reflection.html",
  },
  {
    productName: "swiper 슬라이드 IE 호환성 문제 해결",
    category: 'slide',
    url: "slide/swiper-4.5.1/demos/010-default.html",
  },
  {
    productName: "오직css만을 이용한 슬라이드(auto)",
    category: 'slide',
    url: "slide/css-only_carousel_slider.html",
  },
  {
    productName: "canvas + javascript를 이용한 부드럽게 그라디언트 움직임",
    category: 'background-border',
    category2: 'animation',
    url: "page-bg/background_gradient_embraced.html",
  },
  {
    productName: "배경 이미지의 불투명도를 낮추다",
    category: "background-border",
    category2: "image",
    url: "page-bg/lower_opacity_background_image.html",
  },
  {
    productName: "컨테이너 내부 전체 너비 배경",
    category: 'background-border',
    category2: 'layout',
    url: "page-bg/full-width_background_inside_container.html",
  },
  {
    productName: 'Javascript를 사용하여 전체 화면 모드 켜기 클릭',
    category: 'layout',
    url: 'page-bg/toggle_fullscreen_mode_onclick.html',
  },
  {
    productName: '배경 애니메이션 작은 조명 GSAP',
    category: 'background-border',
    category2: 'animation',
    url: 'page-bg/background_animation_small_light_GSAP.html',
  },
  {
    productName: '크리스마스용 배경 애니메이션 GSAP',
    category: 'background-border',
    category2: 'animation',
    url: 'page-bg/background_animation_christmas_GSAP.html',
  },
  {
    productName: 'GSAP + Barba.js 이용한 페이지 전환 animation',
    category: 'animation',
    url: 'page-bg/page_transition_barbajs_gsap/index.html',
  },
  {
    productName: 'Landing Page Animation GSAP',
    category: 'animation',
    url: 'page-bg/landing_page_animation/index.html',
  },
  {
    productName: 'GSAP를 사용한 사각 입자 애니메이션',
    category: 'background-border',
    category2: 'animation',
    url: 'page-bg/square_particles_animation.html',
  },
  {
    productName: '모바일에서 유닛을 표시하는 요령',
    category: 'layout',
    url: 'page-bg/trick_viewport_units_on_mobile.html',
  },
  {
    productName: '달밤 유성 캔버스 애니메이션',
    category: 'animation',
    url: 'page-bg/moon_night_meteor_canvas_animation.html',
  },
  {
    productName: '배경에 눈내리는(Canvas + Vanilla JS',
    category: 'animation',
    category2: 'background-border',
    url: 'page-bg/falling_snow_animations.html',
  },
  {
    productName: '대각선 줄무늬 지우기 애니메이션',
    category: 'animation',
    category2: 'background-border',
    url: 'page-bg/diagonal_stripes_wipe_animation.html',
  },
  {
    productName: 'CSS 속성이 1개뿐인 풀 다크 모드?!',
    category: 'layout',
    url: 'page-bg/full_dark_mode_only_css.html',
  },
  {
    productName: '3개 이미지가 겹쳐서 웨이브하는 background',
    category: 'animation',
    category2: 'background-border',
    url: 'page-bg/wavy_section_animation.html',
  },
  {
    productName: '화살표 모양의 border',
    category: 'background-border',
    url: 'page-bg/zig_zag_border.html',
  },
  {
    productName: 'clip-path 활용한 뾰족한 화살표 헤더 모양',
    category: 'background-border',
    category2: 'layout',
    url: 'page-bg/responsive_pointed_arrow_header_shape.html',
  },
  {
    productName: '스크롤시 숫자 그래프 애니메이션 (Vanilla Js)',
    category: 'chart-graph',
    category2: 'scroll-parallax',
    url: 'text-animate/scrollbar_number_animation_vanila.html',
  },
  {
    productName: '숫자 그래프 애니메이션 (Vanilla Js)',
    category: 'chart-graph',
    url: 'text-animate/number_animation_vanila.html',
  },
  {
    productName: '코너 텍스트 시차 효과(Vanilla Js)',
    category: 'mouse-effect',
    category2: 'text-effect',
    url: 'text-animate/corner_text_parallax.html',
  },
  {
    productName: 'CSS Only Intro 텍스트 애니메이션 효과(only css)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/intro_text_animation_simple_text.html',
  },
  {
    productName: '100년 카운팅 모션(only css)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/100years(only-css).html',
  },
  {
    productName: 'splitting.js 이용한 시간차 점핑 텍스트 animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/splitting_animated_verbs.html',
  },
  {
    productName: 'clip-path circle 안으로 텍스트 지나가는 모션',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/clip-path_circle_and_scrolling_text_animation.html',
  },
  {
    productName: '현재날짜 가져오기',
    category: 'text-effect',
    url: 'text-animate/get_current_date_js.html',
  },
  {
    productName: 'neonlight 텍스트 타이핑 테두리 호버 효과',
    category: 'animation',
    category2: 'mouse-effect',
    url: 'text-animate/text_typing_neon_light_border_animation.html',
  },
  {
    productName: 'text flying 애니메이션(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/flying_text_animation_GSAP.html',
  },
  {
    productName: 'box형태로 텍스트 밑줄긋기 애니메이션(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/Text_GSAP_animation.html',
  },
  {
    productName: 'box형태로 텍스트 밑줄긋기 애니메이션2(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/swesome_text_effect_animation_gsap.html',
  },
  {
    productName: 'rainbow text animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/rainbow_text_animation.html',
  },
  {
    productName: '순차적 커졌다 작아지는 텍스트 animation (AnimeJS)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/big_small_text_animation.html',
  },
  {
    productName: 'counting - up&down카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/count_up_Down_animation.html',
  },
  {
    productName: 'rolling - 세로로 부드럽게 회전',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/rotating_words.html',
  },
  {
    productName: '오늘 요일 찾기',
    category: 'text-effect',
    url: 'text-animate/find_day_week_javascript.html',
  },
  {
    productName: '지정한 날짜 카운트다운',
    category: 'text-effect',
    url: 'text-animate/countdown_using_javascript.html',
  },
  {
    productName: 'Gradient Text Stroke',
    category: 'text-effect',
    url: 'text-animate/gradient_text_stroke.html',
  },
  {
    productName: '그라디언트 배경 animation',
    category: 'background-border',
    category2: 'animation',
    url: 'text-animate/gradient_background_animation.html',
  },
  {
    productName: 'blur효과가 들어간 좁혀졌다 넓어졌다 animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/text_reveal_animation.html',
  },
  {
    productName: 'repeating-linear-gradient를 이용한 텍스트 패턴 배경',
    category: 'text-effect',
    url: 'text-animate/layered_text_hover.html',
  },
  {
    productName: '그라이언트를 이용한 텍스트 밑줄 한줄만',
    category: 'text-effect',
    url: 'text-animate/low_highlight_text.html',
  },
  {
    productName: 'counting - per를 이용한 weight, bar 카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/weight_count/html.html',
  },
  {
    productName: '3D - 시간 순서에 따라 입체적 노출(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/3D_text_effect_animation_gsap.html',
  },
  {
    productName: 'counting - counterup.js 텍스트 카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/animated_counter_up_effect_redefined.html',
  },
  {
    productName: 'clitch text effect',
    category: 'text-effect',
    url: 'text-animate/clitch_effect.html',
  },
  {
    productName: 'coming soon timer effect1',
    category: 'text-effect',
    url: 'text-animate/coming_soon_js.html',
  },
  {
    productName: 'coming soon timer effect2',
    category: 'text-effect',
    url: 'text-animate/coming_soon_js2.html',
  },
  {
    productName: '3D - isometric text(js)',
    category: 'text-effect',
    url: 'text-animate/css3D_isometric_text_vanilla.html',
  },
  {
    productName: 'hatched shadow text effect',
    category: 'text-effect',
    url: 'text-animate/hatched_text_shadow.html',
  },
  {
    productName: 'intro 부드럽게 노출 enter클릭 사라짐',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/inter_text_animation.html',
  },
  {
    productName: '스무스한 느낌으로 늘어났다가 제자리 돌아오는 text',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/simple_text_animation_html_css.html',
  },
  {
    productName: 'rolling - 위로 스무스하게 올라가는 text',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/sliding_text_animation.html',
  },
  {
    productName: 'reveal bafffle 종이조각 모음(baffle.min.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/text_reveal_animation_bafffle.html',
  },
  {
    productName: 'css만을 이용한 타자치는 느낌',
    category: 'text-effect',
    category2: 'animation',
    url: 'text-animate/typewiter_effect_css.html',
  },
  {
    productName: 'scrollTrigger - GSAP의 ScrollTrigger 플러그인을 사용하여 페이지 스크롤에 요소 표시',
    category: 'scroll-parallax',
    url: 'scroll-parallax/reveal_elements_on_page_scroll.html',
  },
  {
    productName: 'fullpage - 풀페이지 반응형 구간에 따라 풀페이지 죽이고 살리기',
    category: 'scroll-parallax',
    url: 'scroll-parallax/fullpage.js_destory_and_rebuild_base.html',
  },
  {
    productName: 'scrollTrigger - 스크롤 콘텐츠에 대한 고정 탐색 중지(js)',
    category: 'scroll-parallax',
    url: 'scroll-parallax/stop_fixed_navigations_covering_content_scroll.html',
  },
  // {
  //   productName: '',
  //   category: '',
  //   url: '',
  // },
]