let items = [
  {
    productName: "item정렬 방식 flex vs grid",
    category: 'layout',
    url: 'html/flex_grid_item_layout_compare.html',
  },
  {
    productName: "CSS로 목록 스타일을 개선하는 2가지 방법",
    category: "basic",
    url: 'html/2ways_improve_list_styling.html',
  },
  {
    productName: "div 요소의 내용 인쇄",
    category: "basic",
    url: 'html/print_contents_div_element.html',
  },
  {
    productName: "grid를 이용한 덜 절대적인 위치 잡기",
    category: 'layout',
    url: 'html/grid/absolute_positioning_modern.html',
  },
  {
    productName: "css focus-visible(:focus 대신 사용)",
    category: 'mouse-effect',
    url: 'html/css_focus-visible(instead-focus).html',
  },
  {
    productName: "css all 속성에 대해서",
    category: "basic",
    url: 'html/css_all.html',
  },
  {
    productName: "반응형 전체 화면 배경",
    category: 'background-border',
    url: 'html/responsive_full-screen_background.html',
  },
  {
    productName: "논리적 속성을 사용하여 더 나은 CSS 작성",
    category: "basic",
    url: 'html/write_better_css_logical_properties.html',
  },
  {
    productName: "투명한 PNG 이미지 그림자 적용",
    category: 'image',
    category2: 'background-border',
    url: 'html/shadows_transparent_PNG.html',
  },
  {
    productName: "프로젝트에서 사용할 수 있는 flexbox 디자인 패턴",
    category: 'layout',
    url: 'html/flex/flexbox_design_patterns_projects.html',
  },
  {
    productName: "css auto-margin 정렬",
    category: 'layout',
    category2: 'layout',
    url: 'html/auto_margin.html',
  },
  {
    productName: "그리드로 쉽게 콘텐츠 겹침",
    category: 'layout',
    url: 'html/grid/easily_overlap_content.html',
  },
  {
    productName: "배경 비디오를 만드는 방법",
    category: 'background-border',
    url: 'html/how_to_create_background_video.html',
  },
  {
    productName: "background-blend-mode에 대해서",
    category: 'background-border',
    url: 'html/css_background_blend_mode.html',
  },
  {
    productName: "css calc() 에 대해서",
    category: "basic",
    url: 'html/css_calc().html',
  },
  {
    productName: "css object-fit을 사용하여 이미지를 제어하는 방법",
    category: 'image',
    url: 'html/css_object-fit.html',
  },
  {
    productName: "미디어 쿼리가 없는 반응형 CSS 그리드!",
    category: 'flex-grid',
    category: 'layout',
    url: 'html/grid/responsive_no_media_queries.html',
  },
  {
    productName: "배경반복 값 space에 대해서",
    category: 'background-border',
    url: 'html/background_repeat_space.html',
    linkType: 'outlink',
  },
  {
    productName: "다른 색상의 CSS 이중 테두리",
    category: 'background-border',
    url: 'html/double_border_width_diffrent_colors.html',
  },
  {
    productName: "영리한 고정 바닥글 기법",
    category: 'layout',
    url: 'html/sticky_footer_technique.html',
  },
  {
    productName: "그림자 그라디언트",
    category: 'background-border',
    url: 'html/grdient_drop_shadow.html',
  },
  {
    productName: "줄무늬 배경",
    category: 'background-border',
    url: 'html/stiped_background_pattern.html',
  },
  {
    productName: "도트 배경",
    category: 'background-border',
    url: 'html/dot_background_pattern.html',
  },
  {
    productName: "css touch-action 한눈에보기",
    category: 'mouse-effect',
    url: 'html/touch-action.html',
  },
  {
    productName: "css 가상요소 선택자 - marker",
    category: 'basic',
    url: 'html/css가상요소_marker.html',
  },
  {
    productName: "mix-blend-mode 사용 예시 (isolation)",
    category: 'background-border',
    url: 'html/css_mix-blend-mode_사용.html',
  },
  {
    productName: "inset을 이용한 full 레이아웃",
    category: 'layout',
    url: 'html/css_inset_layout.html',
  },
  {
    productName: "input에 관하여",
    category: 'form',
    category2: 'basic',
    url: 'html/input.html',
  },
  {
    productName: "유동적인 타이포그래피 css함수 - clamp()",
    category: 'text-effect',
    url: 'html/유동적인_타이포그래피_clamp().html',
  },
  {
    productName: "반전 그림자 표현 reflected text",
    category: 'text-effect',
    url: 'html/reflected_text.html',
  },
  {
    productName: "skeleton screen",
    category: 'icon-loading',
    url: 'html/skeleton_screen.html',
  },
  {
    productName: "skeleton screen 여러개",
    category: 'icon-loading',
    url: 'html/skeleton_screen2.html',
  },
  {
    productName: "flex margin-top 이용한 footer고정",
    category: 'layout',
    url: 'html/footer_flex(margin).html',
  },
  {
    productName: "와인샵 컨셉_반응형 슬라이더(GREENSOCK)",
    category: 'slide',
    url: 'html/wine_shop_concept_responsive_slider.html',
  },
  {
    productName: "응답성이 뛰어난 최소 포트폴리오 웹 사이트",
    category: 'slide',
    url: 'html/minimal_portfolio/index.html',
  },
  {
    productName: "고급스러운 반응형 슬라이드 slick.js",
    category: 'slide',
    url: 'html/responsive_slider_slickjs/index.html',
  },
  {
    productName: "gsap를 이용한 세로로 부드럽게 슬라이드",
    category: 'slide',
    url: 'html/vertical_content_slider.html',
  },
  {
    productName: "수직 카드 슬라이딩 애니메이션(only css)",
    category: 'slide',
    url: 'html/vertical_card_sliding_animation.html',
  },
  {
    productName: "계속 반복되는 한줄이미지 배너(only css)",
    category: 'slide',
    url: 'html/infinite_autoplay_carousel(only-css).html',
  },
  {
    productName: "멀티플 슬라이드 순수 자바스크립트",
    category: 'slide',
    url: 'html/multiple_slideshow_loop.html',
  },
  {
    productName: "이미지 반사 효과 3D 슬라이더",
    category: 'slide',
    url: 'html/3D_image_slider_reflection_Materialize.html',
    linkType: 'outlink',
  },
  {
    productName: "Glide.js를 사용한 놀라운 효과의 이미지 슬라이드",
    category: 'slide',
    url: 'html/glide/index.html',
  },
  {
    productName: "Javascript를 사용 Mousemove에서 이미지 회전 제어",
    category: 'slide',
    url: 'html/control_image_rotation_mousemove.html',
  },
  {
    productName: "circular rotating reflection",
    category: 'slide',
    url: 'html/css_circular_rotating_slider_reflection.html',
  },
  {
    productName: "swiper 슬라이드 IE 호환성 문제 해결",
    category: 'slide',
    url: 'html/swiper-4.5.1/demos/010-default.html',
  },
  {
    productName: "오직css만을 이용한 슬라이드(auto)",
    category: 'slide',
    url: 'html/css-only_carousel_slider.html',
  },
  {
    productName: "canvas + javascript를 이용한 부드럽게 그라디언트 움직임",
    category: 'background-border',
    category2: 'animation',
    url: 'html/background_gradient_embraced.html',
  },
  {
    productName: "배경 이미지의 불투명도를 낮추다",
    category: "background-border",
    category2: "image",
    url: 'html/lower_opacity_background_image.html',
  },
  {
    productName: "컨테이너 내부 전체 너비 배경",
    category: 'background-border',
    category2: 'layout',
    url: 'html/full-width_background_inside_container.html',
  },
  {
    productName: 'Javascript를 사용하여 전체 화면 모드 켜기 클릭',
    category: 'layout',
    url: 'html/toggle_fullscreen_mode_onclick.html',
  },
  {
    productName: '배경 애니메이션 작은 조명 GSAP',
    category: 'background-border',
    category2: 'animation',
    url: 'html/background_animation_small_light_GSAP.html',
  },
  {
    productName: '크리스마스용 배경 애니메이션 GSAP',
    category: 'background-border',
    category2: 'animation',
    url: 'html/background_animation_christmas_GSAP.html',
  },
  {
    productName: 'GSAP + Barba.js 이용한 페이지 전환 animation',
    category: 'animation',
    url: 'html/page_transition_barbajs_gsap/index.html',
  },
  {
    productName: 'Landing Page Animation GSAP',
    category: 'animation',
    url: 'html/landing_page_animation/index.html',
  },
  {
    productName: 'GSAP를 사용한 사각 입자 애니메이션',
    category: 'background-border',
    category2: 'animation',
    url: 'html/square_particles_animation.html',
  },
  {
    productName: '모바일에서 유닛을 표시하는 요령',
    category: 'layout',
    url: 'html/trick_viewport_units_on_mobile.html',
  },
  {
    productName: '달밤 유성 캔버스 애니메이션',
    category: 'animation',
    url: 'html/moon_night_meteor_canvas_animation.html',
  },
  {
    productName: '배경에 눈내리는(Canvas + Vanilla JS',
    category: 'animation',
    category2: 'background-border',
    url: 'html/falling_snow_animations.html',
  },
  {
    productName: '대각선 줄무늬 지우기 애니메이션',
    category: 'animation',
    category2: 'background-border',
    url: 'html/diagonal_stripes_wipe_animation.html',
  },
  {
    productName: 'CSS 속성이 1개뿐인 풀 다크 모드?!',
    category: 'layout',
    url: 'html/full_dark_mode_only_css.html',
  },
  {
    productName: '3개 이미지가 겹쳐서 웨이브하는 background',
    category: 'animation',
    category2: 'background-border',
    url: 'html/wavy_section_animation.html',
  },
  {
    productName: '화살표 모양의 border',
    category: 'background-border',
    url: 'html/zig_zag_border.html',
  },
  {
    productName: 'clip-path 활용한 뾰족한 화살표 헤더 모양',
    category: 'background-border',
    category2: 'layout',
    url: 'html/responsive_pointed_arrow_header_shape.html',
  },
  {
    productName: '스크롤시 숫자 그래프 애니메이션 (Vanilla Js)',
    category: 'chart-graph',
    category2: 'scroll-parallax',
    url: 'html/scrollbar_number_animation_vanila.html',
  },
  {
    productName: '숫자 그래프 애니메이션 (Vanilla Js)',
    category: 'chart-graph',
    url: 'html/number_animation_vanila.html',
  },
  {
    productName: '코너 텍스트 시차 효과(Vanilla Js)',
    category: 'mouse-effect',
    category2: 'text-effect',
    url: 'html/corner_text_parallax.html',
  },
  {
    productName: 'CSS Only Intro 텍스트 애니메이션 효과(only css)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/intro_text_animation_simple_text.html',
  },
  {
    productName: '100년 카운팅 모션(only css)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/100years(only-css).html',
  },
  {
    productName: 'splitting.js 이용한 시간차 점핑 텍스트 animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/splitting_animated_verbs.html',
  },
  {
    productName: 'clip-path circle 안으로 텍스트 지나가는 모션',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/clip-path_circle_and_scrolling_text_animation.html',
  },
  {
    productName: '현재날짜 가져오기',
    category: 'text-effect',
    url: 'html/get_current_date_js.html',
  },
  {
    productName: 'neonlight 텍스트 타이핑 테두리 호버 효과',
    category: 'animation',
    category2: 'mouse-effect',
    url: 'html/text_typing_neon_light_border_animation.html',
  },
  {
    productName: 'text flying 애니메이션(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/flying_text_animation_GSAP.html',
  },
  {
    productName: 'box형태로 텍스트 밑줄긋기 애니메이션(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/Text_GSAP_animation.html',
  },
  {
    productName: 'box형태로 텍스트 밑줄긋기 애니메이션2(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/swesome_text_effect_animation_gsap.html',
  },
  {
    productName: 'rainbow text animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/rainbow_text_animation.html',
  },
  {
    productName: '순차적 커졌다 작아지는 텍스트 animation (AnimeJS)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/big_small_text_animation.html',
  },
  {
    productName: 'counting - up&down카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/count_up_Down_animation.html',
  },
  {
    productName: 'rolling - 세로로 부드럽게 회전',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/rotating_words.html',
  },
  {
    productName: '오늘 요일 찾기',
    category: 'text-effect',
    url: 'html/find_day_week_javascript.html',
  },
  {
    productName: '지정한 날짜 카운트다운',
    category: 'text-effect',
    url: 'html/countdown_using_javascript.html',
  },
  {
    productName: 'Gradient Text Stroke',
    category: 'text-effect',
    url: 'html/gradient_text_stroke.html',
  },
  {
    productName: '그라디언트 배경 animation',
    category: 'background-border',
    category2: 'animation',
    url: 'html/gradient_background_animation.html',
  },
  {
    productName: 'blur효과가 들어간 좁혀졌다 넓어졌다 animation',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/text_reveal_animation.html',
  },
  {
    productName: 'repeating-linear-gradient를 이용한 텍스트 패턴 배경',
    category: 'text-effect',
    url: 'html/layered_text_hover.html',
  },
  {
    productName: '그라이언트를 이용한 텍스트 밑줄 한줄만',
    category: 'text-effect',
    url: 'html/low_highlight_text.html',
  },
  {
    productName: 'counting - per를 이용한 weight, bar 카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/weight_count/html.html',
  },
  {
    productName: '3D - 시간 순서에 따라 입체적 노출(gsap)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/3D_text_effect_animation_gsap.html',
  },
  {
    productName: 'counting - counterup.js 텍스트 카운팅',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/animated_counter_up_effect_redefined.html',
  },
  {
    productName: 'clitch text effect',
    category: 'text-effect',
    url: 'html/clitch_effect.html',
  },
  {
    productName: 'coming soon timer effect1',
    category: 'text-effect',
    url: 'html/coming_soon_js.html',
  },
  {
    productName: 'coming soon timer effect2',
    category: 'text-effect',
    url: 'html/coming_soon_js2.html',
  },
  {
    productName: '3D - isometric text(js)',
    category: 'text-effect',
    url: 'html/css3D_isometric_text_vanilla.html',
  },
  {
    productName: 'hatched shadow text effect',
    category: 'text-effect',
    url: 'html/hatched_text_shadow.html',
  },
  {
    productName: 'intro 부드럽게 노출 enter클릭 사라짐',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/inter_text_animation.html',
  },
  {
    productName: '스무스한 느낌으로 늘어났다가 제자리 돌아오는 text',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/simple_text_animation_html_css.html',
  },
  {
    productName: 'rolling - 위로 스무스하게 올라가는 text',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/sliding_text_animation.html',
  },
  {
    productName: 'reveal bafffle 종이조각 모음(baffle.min.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/text_reveal_animation_bafffle.html',
  },
  {
    productName: 'css만을 이용한 타자치는 느낌',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/typewiter_effect_css.html',
  },
  {
    productName: 'scrollTrigger - GSAP의 ScrollTrigger 플러그인을 사용하여 페이지 스크롤에 요소 표시',
    category: 'scroll-parallax',
    url: 'html/reveal_elements_on_page_scroll.html',
  },
  {
    productName: 'fullpage - 풀페이지 반응형 구간에 따라 풀페이지 죽이고 살리기',
    category: 'scroll-parallax',
    url: 'html/fullpage.js_destory_and_rebuild_base.html',
  },
  {
    productName: 'scrollTrigger - 스크롤 콘텐츠에 대한 고정 탐색 중지(js)',
    category: 'scroll-parallax',
    url: 'html/stop_fixed_navigations_covering_content_scroll.html',
  },
  {
    productName: 'header - 교차로 관찰자가 있는 고정 헤더(js)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/fixed_header_intersection_observer.html',
  },
  {
    productName: 'scrollTrigger - 수평 미디어 스크롤러 생성',
    category: 'scroll-parallax',
    url: 'html/horizontal_media_scroller.html',
  },
  {
    productName: 'scrollTrigger - 스크롤 마지막에 리스트 추가 (lodash.min.js)',
    category: 'scroll-parallax',
    url: 'html/infnite_scrolling_throttled.html',
  },
  {
    productName: 'scrollTrigger - Typography 모션 효과(GSAP)',
    category: 'scroll-parallax',
    category2: 'text-effect',
    url: 'html/scrollTrigger_typography_animation_GSAP.html',
  },
  {
    productName: 'scrollTrigger - scroll 길이에 맞춰 SVG그리기',
    category: 'scroll-parallax',
    category2: 'icon-loading',
    url: 'html/svg_animation_onscroll.html',
  },
  {
    productName: 'parallax - 창의적인 시차 스크롤링(jarallax.js)',
    category: 'scroll-parallax',
    url: 'html/stunning_parallax_scrolling.html',
  },
  {
    productName: 'scrollTrigger - 스크롤시 고정되다가 다시 올라가는 애니메이션(scrollMagic)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/scrollMagic_library_fixed_again_scrolling.html',
  },
  {
    productName: 'ScrollTrigger - GSAP 간단한 사용법',
    category: 'scroll-parallax',
    url: 'html/ScrollTrigger_GSAP_page_scroll.html',
  },
  {
    productName: 'image-more - 스크롤에 대한 무한한 이미지',
    category: 'scroll-parallax',
    category2: 'image',
    url: 'html/infinite_images_on_scroll.html',
  },
  {
    productName: 'scrollbar - 크리에이티브 페이지 스크롤 진행률 표시줄(js)',
    category: 'scroll-parallax',
    url: 'html/creative_page_scroll_progress_bar.html',
  },
  {
    productName: 'header - 스크롤시 헤더 탐색 위로 올리면 다시 노출(js)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/reveal_nav_on_scroll.html',
  },
  {
    productName: 'header - 스크롤 시작하면 헤더 노출 맨위로 올라가면 없어짐(js)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/hide_header_on_scroll_up_show.html',
  },
  {
    productName: 'header - 스크롤시 헤더 탐색 위로 올리면 다시 노출2(js)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/hide_menu_on_scroll_sticky_navbar.html',
  },
  {
    productName: 'shadow - 스크롤시 그림자 노출여부',
    category: 'scroll-parallax',
    url: 'html/gradient_scroll_shadow.html',
  },
  {
    productName: 'progress - 페이지 스크롤시 원형 진행률 표시줄',
    category: 'scroll-parallax',
    url: 'html/page_scroll_percentage_circular_progress_bar.html',
  },
  {
    productName: 'scrollTrigger - 스크롤시 비디오 배경 fadeout',
    category: 'scroll-parallax',
    category2: 'background-border',
    url: 'html/fullscreen_video_background_fadeout_scroll.html',
  },
  {
    productName: 'parallax - 다른 이미지들 순차적적 움직임',
    category: 'scroll-parallax',
    category2: 'image',
    url: 'html/parallax_scrolling_effects_mountain.html',
  },
  {
    productName: 'scrollTrigger - 스크롤시 시차 물결 효과',
    category: 'scroll-parallax',
    category2: 'background-border',
    url: 'html/parallax_water_wave_scrolling_effect.html',
  },
  {
    productName: 'scrollTrigger - 스크롤시 기울어진 배경 평평하게 전환',
    category: 'scroll-parallax',
    category2: 'background-border',
    url: 'html/transform_effects_on_scroll_skewed.html',
  },
  {
    productName: 'scroll-behavior - 탭선택시, 스크롤시 부드러운 화면 스크롤(no js)',
    category: 'scroll-parallax',
    url: 'html/simple_sticky_navbar_smooth_scroll.html',
  },
  {
    productName: 'transform - 스크롤시 상단 동그라미 평평하게',
    category: 'scroll-parallax',
    category2: 'background-border',
    url: 'html/scroll_transform.html',
  },
  {
    productName: 'indicator - 스크롤 길이 체크',
    category: 'scroll-parallax',
    url: 'html/scroll_indicator.html',
  },
  {
    productName: 'scroll-snap - fullpage scroll',
    category: 'scroll-parallax',
    url: 'html/fullpage_scrolling_pure_css_scroll.html',
  },
  {
    productName: 'smooth scrolling - 스크롤시 부드럽게',
    category: 'scroll-parallax',
    url: 'html/add_smooth_scrolling_experience_vanilla.html',
  },
  {
    productName: 'parallax - 다음 장면이 이전 장면을 덮고 형태',
    category: 'scroll-parallax',
    url: 'html/create_a_parallax_scrolling_effects_using_only_htmlcss.html',
  },
  {
    productName: 'scrollTrigger - 스크롤 할수록 보여지는 크게 커짐',
    category: 'scroll-parallax',
    category2: 'icon-loading',
    url: 'html/image_transform_scroll_css3_vanilla.html',
  },
  {
    productName: 'parallax - 간단한 parallax scrolling(no js)',
    category: 'scroll-parallax',
    url: 'html/pure_css_parallax_scrolling_nojs.html',
  },
  {
    productName: 'sticky - 텍스트 상단고정 sticky scrolling',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/pure_css_sticky_scrolling_effects_nojs.html',
  },
  {
    productName: 'progress - scroll indicator 스크롤 크기만틈 변화',
    category: 'scroll-parallax',
    url: 'html/scroll_progress_indicator_with_mouse_follow.html',
  },
  {
    productName: 'sticky - 세로바 풀로 체워지고 텍스트 움직이는 scrolling(no js)',
    category: 'scroll-parallax',
    category2: 'background-border',
    url: 'html/scrolling_sticky_텍스트움직임.html',
  },
  {
    productName: 'scrollTrigger - scrolling 전체영역 한칸씩 덮기(gsap)',
    category: 'scroll-parallax',
    category2: 'layout',
    url: 'html/Smooth_scrolling_on_full_landing_sections.html',
  },
  {
    productName: '쿠키 동의',
    category: 'popup',
    url: 'html/cookie_consent_banner.html',
  },
  {
    productName: 'backdrop and dialog animation',
    category: 'popup',
    url: 'html/animating_dialog_and_backdrop.html',
  },
  {
    productName: 'HTML CSS(:target)를 사용한 팝업 창',
    category: 'popup',
    url: 'html/popup_window_css_target_using.html',
  },
  {
    productName: '동일한 target 값으로 열고 닫기',
    category: 'popup',
    url: 'html/custom_alert_popup_js.html',
  },
  {
    productName: '화살표 함수를 이용한 열고 닫기',
    category: 'popup',
    url: 'html/popup-share_modal.html',
  },
  {
    productName: 'mousemove - 스크래치 카드',
    category: 'mouse-effect',
    url: 'html/scratch_card_with_javascript.html',
  },
  {
    productName: 'active - Easiest 3D 버튼',
    category: 'mouse-effect',
    url: 'html/easiest_3D_button.html',
  },
  {
    productName: 'mouse - 스와이프 방향을 감지하는 방법(Javascript)',
    category: 'mouse-effect',
    url: 'html/how_to_detect_swipe_direction.html',
  },
  {
    productName: 'mouse - 터치 스크린을 감지(Javascript)',
    category: 'mouse-effect',
    url: 'html/how_to_detect_touch_screen.html',
  },
  {
    productName: 'hover - 틸팅 카드(only-css)',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/tilting_card_hover.html',
  },
  {
    productName: 'click - Google 버튼 클릭 효과(js)',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/google_button_click_effect.html',
  },
  {
    productName: 'click - 외/내부 클릭 감지',
    category: 'mouse-effect',
    url: 'html/detect_click_outside_inside.html',
  },
  {
    productName: 'hover - CSS 글라스 모피리즘',
    category: 'mouse-effect',
    url: 'html/glassmorphism_button_hover.html',
  },
  {
    productName: 'hover - 호버에 테두리 그리기 CSS',
    category: 'mouse-effect',
    category2: 'background-border',
    url: 'html/draw_border_hover_CSS_border_animation.html',
  },
  {
    productName: 'hover - 채워지는 배경의 모션이 통통튀는',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/awesome_hover_buttons.html',
  },
  {
    productName: 'hover - 양쪽으로 고무줄처럼 늘어나고 텍스트 점핑 GSAP',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/read_more_button.html',
  },
  {
    productName: 'hamburger - 라인이 fade 효과가 들어간',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/hamburger_button_toggle.html',
  },
  {
    productName: 'hamburger - 회전을 빨리하며 노멀한2',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/hamburger_pure_css_menu2.html',
  },
  {
    productName: 'hamburger - 회전을 빨리하며 노멀한',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/hamburger_pure_css_menu.html',
  },
  {
    productName: 'hamburger - 당기는듯한 다이나믹',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/hamburger_icon_css3_animation.html',
  },
  {
    productName: 'hover - 박스안을 원이 커지며 채워지는',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/circle_inside_box_grows_fills.html',
  },
  {
    productName: 'hamburger - 최신 애니메이션 메뉴 토글 버튼',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/toggle_button_modern_animated_menu.html',
  },
  {
    productName: 'mousemove - CSS 사용자 정의 속성을 동적으로 만들기',
    category: 'mouse-effect',
    url: 'html/making_css_custom_properties_dynamic.html',
  },
  {
    productName: 'hover - 3D형태의 카드 이미지로 뒤집기',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/3D_flip_card_image_hover.html',
  },
  {
    productName: 'click - lottiefile을 이용한 축하 불꽃',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/add_amazing_animations_lottiefile.html',
  },
  {
    productName: 'hover - 박스 테두리 라인 선긋기',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/advanced_hover_animation.html',
  },
  {
    productName: 'hover - 텍스트 영역 안에서 움직이고 텍스트도 마우스 움직임에 따라 조금씩 움직임',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/animated_cursor_cool_link_hover_effect.html',
  },
  {
    productName: 'hover - 원 마우스 따라다니며 텍스트에 접근하면 박스처리',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/button_hover_effect_vanilla.html',
  },
  {
    productName: 'hover - box shadow이용 이중 테두리',
    category: 'mouse-effect',
    category2: 'background-border',
    url: 'html/cool_css_box-shadow_hover.html',
  },
  {
    productName: 'click - tweenmax이용 전체화면 덥으며 메뉴 순차적 노출',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/Creating_a_full_screen_navigation_gsap3.html',
  },
  {
    productName: 'hover - 텍스트 위/아래 박스 채워짐',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/creative_menu_item_hover_html_css.html',
  },
  {
    productName: 'hover - 3D 겹쳐 있는 박스 계산 형태로 보임',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/css3D_isometric_social_media_icon_hover.html',
  },
  {
    productName: 'hover - 버튼 테두리 라인치기',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/draw_border_hover.html',
  },
  {
    productName: 'hover - 눈알 따라다님 입움직임',
    category: 'mouse-effect',
    url: 'html/eyes_follow_mouse_cursor_vanilla.html',
  },
  {
    productName: 'gradien glowing 그림자',
    category: 'background-border',
    category2: 'animation',
    url: 'html/glowing_gradien_border_animation.html',
  },
  {
    productName: 'background up fill',
    category: 'background-border',
    category2: 'animation',
    url: 'html/hover_background_color_up_fill.html',
  },
  {
    productName: '글씨 색 채움 이미지 부드럽게 노출 (tweenmax)',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/hover-text_image_effect_gsap.html',
  },
  {
    productName: 'mouseMove - 마우스 좌우 움직임에 따라 이미지 보임',
    category: 'mouse-effect',
    category2: 'image',
    url: 'html/image_comparision_slider_vanilla.html',
  },
  {
    productName: 'hover - 커서의 처음을 기준으로 채움',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/mouseenter_mouseout_background_fill.html',
  },
  {
    productName: 'pixel 형태로 채움',
    category: 'background-border',
    category2: 'animation',
    url: 'html/pixel_button_hover_animation.html',
  },
  {
    productName: '회색 우에서좌로 자연스럽게 컬러보임',
    category: 'image',
    category2: 'animation',
    url: 'html/simple_image_hover.html',
  },
  {
    productName: 'hover - 배경색 텍스트색 교차 change',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/text_hover_back_color_change.html',
  },
  {
    productName: 'menu - PC메뉴를 복사하여 모바일용 메뉴 구현하기',
    category: 'navigation-list',
    url: 'html/pc-clone_mobile_menu.html',
  },
  {
    productName: 'menu - 반응형 구간에서는 작동하지 않는 메뉴 애니메이션',
    category: 'navigation-list',
    url: 'html/2depth_hover_submenu.html',
  },
  {
    productName: 'menu - 팝업 코너 메뉴',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/pop_out_corner_menu.html',
  },
  {
    productName: 'menu - 사용자 지정 선택 메뉴 만들기',
    category: 'navigation-list',
    url: 'html/custom_select_menu.html',
  },
  {
    productName: 'menu - hover한 버튼 박스형태로 따라다니기',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/sns_buttons_interaction.html',
  },
  {
    productName: 'menu - 반응형 스틱네비게이션 바',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/responsive_sticky_navigation_bar.html',
  },
  {
    productName: 'menu - gsap 사용한 최소한의 풀스크린 내비게이션',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/fullscreen_navigation_gsap/index.html',
  },
  {
    productName: 'menu - 물흐르는듯한 끈적한 효과',
    category: 'navigation-list',
    category2: 'animation',
    url: 'html/menu_social_icon_gooey_effects.html',
  },
  {
    productName: '선택된 메뉴 bar 따라다니기',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/menu_indicator_animate.html',
  },
  {
    productName: 'ios 스타일 슬라이딩',
    category: 'layout',
    category2: 'animation',
    url: 'html/menu_ios_style_sliding.html',
  },
  {
    productName: '리스트 순서 이동',
    category: 'mouse-effect',
    category2: 'navigation-list',
    url: 'html/drag_drop_list_js_draggable.html',
  },
  {
    productName: 'menu - 검색 필드가 있는 응답형 드롭다운 메뉴 표시줄(only css)',
    category: 'navigation-list',
    url: 'html/menu_dropdown_search_field_responsive.html',
  },
  {
    productName: '반응성 필터 가능 이미지 갤러리',
    category: 'navigation-list',
    url: 'html/list_responsive_filterable_image_gallery.html',
  },
  {
    productName: 'list - JavaScript를 사용한 Todo List 목록',
    category: 'navigation-list',
    url: 'html/todo_list_javaScript.html',
  },
  {
    productName: 'gsap를 이용한 svg gooey pagination2',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/gooey_pagination2.html',
  },
  {
    productName: 'gsap를 이용한 gooey pagination',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'html/gooey_pagination.html',
  },
  {
    productName: 'menu - 반응형 상단고정 navbar 선택시 노출모션',
    category: 'navigation-list',
    url: 'html/responsive_fixed_navigation_bar.html',
  },
  {
    productName: 'accordion - css, js 이용 faq스타일',
    category: 'navigation-list',
    url: 'html/accordion_faq_es6.html',
  },
  {
    productName: 'tweenmax를 이용한 전체 화면이 움직임',
    category: 'layout',
    category2: 'animation',
    url: 'html/minimal_navigation_html_css_jquery_gsap.html',
  },
  {
    productName: 'tweenmax를 이용한 메뉴 선택시 전체를 덮으면서 메뉴 노출',
    category: 'layout',
    category2: 'animation',
    url: 'html/responsive_dropdown_navigation_menu.html',
  },
  {
    productName: 'ribbon - 박스 모서리 리본 모양을 만드는 방법',
    category: 'icon-loading',
    url: 'html/make_ribbon_shape.html',
  },
  {
    productName: '빛나는 그라데이션 로드 바 애니메이션',
    category: 'background-border',
    category2: 'animation',
    url: 'html/glowing_gradient_loading_bar_animation.html',
  },
  {
    productName: 'Rainy Cloud 애니메이션 효과',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/rainy_cloud_animation.html',
  },
  {
    productName: '--i, box-shadow을 활용한 흩어졌다 다시 모이는 애니메이션',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/circle_animation_hover_css.html',
  },
  {
    productName: '3D박스 그래프처럼 아래위로 움직임',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/cube_single_div_sinking.html',
  },
  {
    productName: 'bounce - 그림자와 함께 다이나믹하게 통통 튀는 느낌',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/bouncing_ball_animation.html',
  },
  {
    productName: '흔들흔들 종모양 알람',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/bell_notification.html',
  },
  {
    productName: 'cartoon - 반갈라진 계란 그리기',
    category: 'icon-loading',
    url: 'html/picture_egg.html',
  },
  {
    productName: 'cartoon - 지구를 도는 로켓 animation',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/rocket_circle_animation.html',
  },
  {
    productName: '박스가 구르는 애니메이션(only css)',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/box_rolls_animation.html',
  },
  {
    productName: '3D - 회전 이미지 큐브 애니메이션',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/3D_rotating_cube_animation.html',
  },
  {
    productName: 'cartoon - 뜨거워서 피어오르는 연기',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/animated_hot_smoke.html',
  },
  {
    productName: '하트 접기 애니메이션',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/heart_loading_animation.html',
  },
  {
    productName: 'loading - 동그라미 교차 로딩',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/circle_mov_animation.html',
  },
  {
    productName: 'star - CSS를 사용한 분수 SVG 별',
    category: 'icon-loading',
    url: 'html/fractional_SVG_stars.html',
  },
  {
    productName: '3D - 아이소메트릭 큐브',
    category: 'icon-loading',
    url: 'html/isometric_cube.html',
  },
  {
    productName: '박스 주변 테두리로 라인회전 animation',
    category: 'background-border',
    category2: 'animation',
    url: 'rotating_border_animation.html',
  },
  {
    productName: '뾰족한 그림자가 양끝에 나와있는 카드',
    category: 'background-border',
    url: 'html/creative_website_card_effects.html',
  },
  {
    productName: 'cartoon - css만 이용해 물방울 모양 그리기',
    category: 'icon-loading',
    url: 'html/water_drops_drawing.html',
  },
  {
    productName: 'flower - 색종이 떨어지는 애니메이션',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/confetti_fallling.html',
  },
  {
    productName: 'line - SVG그리기 애니메이션',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/svg_stroke_animation.html',
  },
  {
    productName: 'wifi animation',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/wifi_loading_animation.html',
  },
  {
    productName: 'loading 문구 순차적 wave',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/wavy_text_animation.html',
  },
  {
    productName: 'shadow - flat long box shadow(js)',
    category: 'background-border',
    url: 'html/text-flat_long_box_shadow_vanilla.html',
  },
  {
    productName: 'bounce - 힘없이 공이 떨어지는',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/bounce_animation.html',
  },
  {
    productName: 'bounce - 공이 통통 튀는',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/bouncing_ball.html',
  },
  {
    productName: 'bubble - background 비눗방울 전체 날림',
    category: 'background-border',
    category2: 'animation',
    url: 'html/bubble_animation_background.html',
  },
  {
    productName: 'loading - 원2개가 겹친 상태에서 크게 작게',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/cool_css_loading_animation.html',
  },
  {
    productName: 'mouse - 3가지 형태의 스크롤 유도모션',
    category: 'icon-loading',
    url: 'html/cool_scroll_icon_animation.html',
  },
  {
    productName: 'loading - 서서히 퍼지면서 알람',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/css_pulse_animation.html',
  },
  {
    productName: '전체화면 게이지 채우면서 100',
    category: 'text-effect',
    category2: 'icon-loading',
    url: 'html/full_screen_pre-loader_using.html',
  },
  {
    productName: '좌상단을 꼭지점으로 매달리다 떨이지는',
    category: 'text-effect',
    category2: 'animation',
    url: 'html/hinge_animation.html',
  },
  {
    productName: 'cartoon - 모래시계',
    category: 'icon-loading',
    url: 'html/hourglass-drawing_width_css_vanilla.html',
  },
  {
    productName: 'icon - 물방울',
    category: 'icon-loading',
    url: 'html/howtodraw_drop_css.html',
  },
  {
    productName: 'icon - 라운드가 있는 하트',
    category: 'icon-loading',
    url: 'html/howtodraw_heart_css2.html',
  },
  {
    productName: 'icon - 일반적인 하트',
    category: 'icon-loading',
    url: 'html/howtodraw_heart_css.html',
  },
  {
    productName: 'fireworks - 축하 꽃가루',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/simple_stick_fireworks.html',
  },
  {
    productName: 'loading - 배터리 채워지는',
    category: 'icon-loading',
    category2: 'animation',
    url: 'html/single_element_battery_animation.html',
  },
  {
    productName: 'checkbox - v checked style animated3',
    category: 'form',
    category2: 'animation',
    url: 'html/material_ui_style_animated_checkboxes4.html',
  },
  {
    productName: 'validation - 패턴으로 검증(only-css)',
    category: 'form',
    url: 'html/validation_with_patterns.html',
  },
  {
    productName: 'clock - selectbox를 활용한 간단한 알람시계 구축(js)',
    category: 'form',
    url: 'html/alarm_clock/index.html',
  },
  {
    productName: 'calendar - 순수 자바스크립트로 만든 달력',
    category: 'calendar',
    url: 'html/full_calendar_javaScript.html',
  },
  {
    productName: '입력 필드를 누를 때 입력 필드 텍스트 선택',
    category: 'form',
    url: 'html/select_all_text_input_clicked.html',
  },
  {
    productName: 'Copy - 입력 요소에서 클립보드로 복사',
    category: 'form',
    url: 'html/copy_clipboard_input_element.html',
  },
  {
    productName: 'upload - 업로드하기 전에 여러 이미지 미리 보기',
    category: 'form',
    url: 'html/rpeview_multiple_images_before_upload.html',
  },
  {
    productName: '두 날짜 사이의 일 계산기',
    category: 'form',
    url: 'html/days_between_two_dates_calculator.html',
  },
  {
    productName: 'select - 사용자 지정 선택 메뉴',
    category: 'form',
    category2: 'navigation-list',
    url: 'html/select_custom_menu.html',
  },
  {
    productName: 'checkbox - v checked style animated2',
    category: 'form',
    category2: 'animation',
    url: 'html/material_ui_style_animated_checkboxes2.html',
  },
  {
    productName: 'input - HTML CSS & JavaScript로 사전 앱 구축 close버튼',
    category: 'form',
    url: 'html/build_dictionary_app.html',
  },
  {
    productName: 'select - 멋진 드롭다운 목록 상호 작용',
    category: 'form',
    category2: 'animation',
    url: 'html/awesome_dropdown_list_interaction.html',
  },
  {
    productName: 'slider - 최소값 범위 슬라이더(H 단위) 입력값',
    category: 'form',
    url: 'html/price_range_slider_min-max_input.html',
  },
  {
    productName: 'input - 태그 추가 입력 상자',
    category: 'form',
    url: 'html/add_tags_input_box.html',
  },
  {
    productName: 'slider - heart 색 채우기 슬라이더',
    category: 'form',
    url: 'html/heart_range_slider.html',
  },
  {
    productName: '입력시 Caps Lock 감지',
    category: 'form',
    url: 'html/how_to_detect_caps_lock_on.html',
  },
  {
    productName: 'input - 검색된 텍스트 강조',
    category: 'form',
    url: 'html/highlight_searched_text.html',
  },
  {
    productName: '+ or - 선택 스테퍼',
    category: 'form',
    url: 'html/input_stepper.html',
  },
  {
    productName: 'input - 현재 입력 암호 재입력 확인',
    category: 'form',
    url: 'html/confirm_password_validation.html',
  },
  {
    productName: 'checkbox - 이모지 별점 위젯(only css)',
    category: 'form',
    url: 'html/emoji_star_rating_widget.html',
  },
  {
    productName: 'slider - 맞춤형 이모지 범위 슬라이더',
    category: 'form',
    url: 'html/custom_emoji_range_slider.html',
  },
  {
    productName: 'input - 입력 문자수 체크 제한',
    category: 'form',
    url: 'html/limit_Input_characters_javaScript.html',
  },
  {
    productName: 'input - 이메일 유효성 검사',
    category: 'form',
    url: 'html/check_email_validation_javascript.html',
  },
  {
    productName: 'slider - 멀티 핸들 레인지 슬라이더',
    category: 'form',
    url: 'html/multi_handle_range_slider.html',
  },
  {
    productName: 'input - 비밀번호 공개 입력 옵션',
    category: 'form',
    url: 'html/options_password_revealing_inputs.html',
  },
  {
    productName: 'checkbox - box-shadow을 이용한 체크박스 animation',
    category: 'form',
    category2: 'animation',
    url: 'html/checkbox_box-shadow.html',
  },
  {
    productName: 'checkbox - 경계 반경 변경하는 체크박스',
    category: 'form',
    category2: 'animation',
    url: 'html/checkbox_border-radius.html',
  },
  {
    productName: 'checkbox - box 3D 회전하는 체크박스',
    category: 'form',
    category2: 'animation',
    url: 'html/checkbox_3d_rotation.html',
  },
  {
    productName: 'html/input - js필요할거 같지만 필요없는 입력요소',
    category: 'form',
    url: 'html/No-JS_typing_suggestions.html',
  },
  {
    productName: 'input - 검색입력 Google 검색 엔진 적용',
    category: 'form',
    url: 'html/google_search_engine.html',
  },
  {
    productName: 'checkbox - 체크박스 전체선택 여부 확인',
    category: 'form',
    url: 'html/checkbox_selectchecked.html',
  },
  {
    productName: 'input - 돋보기 hover 입력할 수 있도록 커짐',
    category: 'form',
    category2: 'animation',
    url: 'html/morphing_form_search_icon_to_search_bar.html',
  },
  {
    productName: 'textarea - 쓰는 글의 크기만큼 자동 리사이징',
    category: 'form',
    url: 'html/live_character_count_es6.html',
  },
  {
    productName: 'input - placeholder focus 입력박스 바깥으로 움직임',
    category: 'form',
    category2: 'animation',
    url: 'html/animated_input_label_using.html',
  },
  {
    productName: 'input - 돋보기 hover 검색 입력박스 확장 움직임',
    category: 'form',
    category2: 'animation',
    url: 'html/awesome_css_search_box_html_css.html',
  },
  {
    productName: 'checkbox - omlet switch checkbox animate',
    category: 'form',
    category2: 'animation',
    url: 'html/custom_omlet_switch_checkbox.html',
  },
  {
    productName: 'checkbox - X -> V animate',
    category: 'form',
    category2: 'animation',
    url: 'html/custome_toggle_animated.html',
  },
  {
    productName: 'input - file-upload drag drop 미리보기',
    category: 'form',
    url: 'html/file-upload_drag_drop_browse.html',
  },
  {
    productName: 'input - glassmorphism form design',
    category: 'form',
    category2: 'background-border',
    url: 'html/form-glassmorphism.html',
  },
  {
    productName: 'input - 입력박스 안 값 복사',
    category: 'form',
    url: 'html/form-input_copy.html',
  },
  {
    productName: 'input - 입력박스 값 리스트 형태로 추가&삭제',
    category: 'form',
    url: 'html/list-to_do_list_js.html',
  },
  {
    productName: 'input - 입력시 미리 지정한 값에 맞는 단어 자동 완성',
    category: 'form',
    url: 'html/search_bar_auto-complete_suggestions_js.html',
  },
  {
    productName: 'input - 비밀번호 입력값 보기 끄기, 입력란 배경색 바뀌는 animate',
    category: 'form',
    category2: 'animate',
    url: 'html/show_hide_password_stunning_transitions_js.html',
  },
  {
    productName: 'input - 비밀번호 입력값 보기 끄기',
    category: 'form',
    url: 'html/show_hide_password_toggle.html',
  },
  {
    productName: '겹치는 막대 차트',
    category: 'chart-graph',
    url: 'html/overlapping_bar_chart.html',
  },
  {
    productName: '원 그라데이션 경계 애니메이션(only-css)',
    category: 'background-border',
    category2: 'animation',
    url: 'html/circle_gradient_border_animation.html',
  },
  {
    productName: 'jquery-circle-progress 이용한 동그라미 진행률',
    category: 'chart-graph',
    url: 'html/circular_progress_bar_jquery.html',
  },
  {
    productName: '동적 동그라미 진행률(conic-gradient)',
    category: 'chart-graph',
    url: 'html/dynamic_circular_progress_bar.html',
  },
  {
    productName: '멋진 타임 타이머(jquery)',
    category: 'chart-graph',
    url: 'html/awesome_time_timer.html',
  },
  {
    productName: 'Javascript를 사용한 제품 필터 및 검색',
    category: 'form',
    url: 'html/product_filter_search_javascript.html',
  },
  {
    productName: 'CSS 마스크 및 클립 경로 속성을 사용하여 모서리를 자르는 트릭',
    category: 'background-border',
    url: 'html/cut_corners_mask_clip-path_properties.html',
  },
  {
    productName: '픽셀 타일 이미지 아트(Only Css)',
    category: 'image',
    url: 'html/pixel_image_pixelated_tiles.html',
  },
  {
    productName: '사용자 브라우저 및 OS 검색',
    category: 'basic',
    url: 'html/detect_user_browser_os_using.html',
  },
  {
    productName: '키 누르기 및 키 코드 검색',
    category: 'basic',
    url: 'html/detect_key_presses_key_code.html',
  },
  {
    productName: '세로로 잘라지면서 3D Flip animation',
    category: 'image',
    url: 'html/3Dflip_hover_animation.html',
  },  
  {
    productName: 'SVG TV 노이즈 효과',
    category: 'etc',
    url: 'html/SVG_TV_noise_effects.html',
  },
  {
    productName: '3D flip santa card',
    category: 'etc',
    category2: 'animation',
    url: 'html/3D_flip_santa_card.html',
  },
  {
    productName: 'OTP 입력 필드',
    category: 'form',
    url: 'html/otp_input_field.html',
  },
  {
    productName: '무한으로 흐르는 컨텐츠 (only css)',
    category: 'slide',
    url: 'html/css_marquee.html',
  },
  {
    productName: '무한으로 흐르는 컨텐츠 - 가로 (only css)',
    category: 'slide',
    url: 'html/css_marquee.html',
  },
  {
    productName: '무한으로 흐르는 컨텐츠 - 세로 (only css)',
    category: 'slide',
    url: 'html/css_marquee_vertical.html',
  },
  {
    productName: '무한으로 흐르는 컨텐츠 토글 - 세로 (only css)',
    category: 'slide',
    url: 'html/css_marquee_wall.html',
  },
  // {
  //   productName: '',
  //   category: '',
  //   url: 'html/',
  // },
]