let outlink = [  
  {
    productName: "Testing the New CSS Reset",
    category: "basic",
    url: "https://codepen.io/robinrendle/pen/VwzPJrL?editors=1100",
    linkType: 'outlink',
  },
  {
    productName: "처음으로 css grid 배우기",
    category: 'layout',
    url: "https://dev.to/thouravi/learning-css-grid-for-the-first-time-5amb",
    linkType: 'outlink',
  },
  {
    productName: "@supports selector()",
    category: 'basic',
    category2: 'css-trick',
    url: "https://css-tricks.com/supports-selector/",
    linkType: 'outlink',
  },
  {
    productName: "CSS scroll-behavior",
    category: 'css-trick',
    category2: 'scroll-parallax',
    url: "https://css-tricks.com/almanac/properties/s/scroll-behavior/",
    linkType: 'outlink',
  },
  {
    productName: "CSS 재설정으로 :where() 의 특수성 사용",
    category: 'css-trick',
    category2: 'basic',
    url: "https://css-tricks.com/using-the-specificity-of-where-as-a-css-reset/",
    linkType: 'outlink',
  },
  {
    productName: ":fullscreen 선택자",
    category: 'css-trick',
    category2: 'basic',
    url: "https://css-tricks.com/almanac/selectors/f/fullscreen/",
    linkType: 'outlink',
  },
  {
    productName: "종속성 없이 순수 JavaScript로 작성된 가볍고 강력하며 유연한 슬라이더(splide)",
    category: 'slide',
    url: "https://splidejs.com/",
    linkType: 'outlink',
  },
  {
    productName: "가장 현대적인 모바일 터치 슬라이더 - swiper",
    category: 'slide',
    url: "https://swiperjs.com/",
    linkType: 'outlink',
  },
  {
    productName: "js가 가벼운 자동정지/시작이 가능한 슬라이드(glide)",
    category: 'slide',
    url: "https://glidejs.com/",
    linkType: 'outlink',
  },
  {
    productName: "js가 가벼운 슬라이드(glider)",
    category: 'slide',
    url: "https://nickpiscitelli.github.io/Glider.js/",
    linkType: 'outlink',
  },
  {
    productName: '끌어당기며 새로고침 해주는 PulltoRefresh.js',
    category: 'layout',
    url: 'https://www.boxfactura.com/pulltorefresh.js/',
    linkType: 'outlink',
  },
  {
    productName: '5분 만에 어두운 모드, 반전된 밝기 변수 사용',
    category: 'layout',
    url: 'https://lea.verou.me/2021/03/inverted-lightness-variables/',
    linkType: 'outlink',
  },
  {
    productName: '텍스트 분활 애니메이션(splitting.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://splitting.js.org/',
    linkType: 'outlink',
  },
  {
    productName: '타자치는 애니메이션(t.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://mntn-dev.github.io/t.js/',
    linkType: 'outlink',
  },
  {
    productName: '네온사인 애니메이션(novacancy.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://github.com/chuckyglitch/novacancy.js/',
    linkType: 'outlink',
  },
  {
    productName: '모자이크 애니메이션(baffle.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://camwiegert.github.io/baffle/',
    linkType: 'outlink',
  },
  {
    productName: 'parallax - 자바 스크립트로 시차 효과를 얻는 가장 쉬운 방법 simplePARALLAX.js',
    category: 'scroll-parallax',
    url: 'https://simpleparallax.com/',
    linkType: 'outlink',
  },
  {
    productName: '애니메이션 중 스크롤바 숨기기(css-tricks)',
    category: 'scroll-parallax',
    category2: 'css-trick',
    url: 'https://css-tricks.com/hide-scrollbars-during-an-animation/',
    linkType: 'outlink',
  },
  {
    productName: 'scrollTrigger - AOS 애니메이션 sample(codepen)',
    category: 'scroll-parallax',
    url: 'https://codepen.io/letsbleachthis/pen/zewKYE',
    linkType: 'outlink',
  },
  {
    productName: 'parallax - 경량의 js Library(Rellax.js)',
    category: 'scroll-parallax',
    url: 'https://dixonandmoe.com/rellax/',
    linkType: 'outlink',
  },
  {
    productName: '플로팅 요소를 생성을 위한 툴킷 (floating-ui)',
    category: 'layout',
    url: 'https://floating-ui.com/',
    linkType: 'outlink',
  },
  {
    productName: '애니메이션 툴팁 추가(tippy.js)',
    category: 'popup',
    url: 'https://atomiks.github.io/tippyjs/',
    linkType: 'outlink',
  },
  {
    productName: 'hover - jQuery를 위한 60+fps 경량 시차 호버 효과 - tilt.js',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'https://gijsroge.github.io/tilt.js/',
    linkType: 'outlink',
  },
  {
    productName: 'hover 라이브러리(hover.css)',
    category: 'mouse-effect',
    category2: 'animation',
    url: 'https://ianlunn.github.io/Hover/',
    linkType: 'outlink',
  },
  // {
  //   productName: '',
  //   category: '',
  //   url: '',
  //   linkType: 'outlink',
  // },
]