let outlink = [  
  {
    productName: "Testing the New CSS Reset",
    category: "basic",
    url: "https://codepen.io/robinrendle/pen/VwzPJrL?editors=1100",
    linkType: 'outlink',
  },
  {
    productName: "처음으로 css grid 배우기",
    category: 'flex-grid',
    url: "https://dev.to/thouravi/learning-css-grid-for-the-first-time-5amb",
    linkType: 'outlink',
  },
  {
    productName: "@supports selector()",
    category: 'basic',
    category2: 'css-trick',
    url: "https://css-tricks.com/supports-selector/",
    linkType: 'outlink',
  },
  {
    productName: "CSS scroll-behavior",
    category: 'css-trick',
    category2: 'scroll-parallax',
    url: "https://css-tricks.com/almanac/properties/s/scroll-behavior/",
    linkType: 'outlink',
  },
  {
    productName: "CSS 재설정으로 :where() 의 특수성 사용",
    category: 'css-trick',
    category2: 'basic',
    url: "https://css-tricks.com/using-the-specificity-of-where-as-a-css-reset/",
    linkType: 'outlink',
  },
  {
    productName: ":fullscreen 선택자",
    category: 'css-trick',
    category2: 'basic',
    url: "https://css-tricks.com/almanac/selectors/f/fullscreen/",
    linkType: 'outlink',
  },
  {
    productName: "종속성 없이 순수 JavaScript로 작성된 가볍고 강력하며 유연한 슬라이더(splide)",
    category: 'slide',
    url: "https://splidejs.com/",
    linkType: 'outlink',
  },
  {
    productName: "가장 현대적인 모바일 터치 슬라이더 - swiper",
    category: 'slide',
    url: "https://swiperjs.com/",
    linkType: 'outlink',
  },
  {
    productName: "js가 가벼운 자동정지/시작이 가능한 슬라이드(glide)",
    category: 'slide',
    url: "https://glidejs.com/",
    linkType: 'outlink',
  },
  {
    productName: "js가 가벼운 슬라이드(glider)",
    category: 'slide',
    url: "https://nickpiscitelli.github.io/Glider.js/",
    linkType: 'outlink',
  },
  {
    productName: '끌어당기며 새로고침 해주는 PulltoRefresh.js',
    category: 'layout',
    url: 'https://www.boxfactura.com/pulltorefresh.js/',
    linkType: 'outlink',
  },
  {
    productName: '5분 만에 어두운 모드, 반전된 밝기 변수 사용',
    category: 'layout',
    url: 'https://lea.verou.me/2021/03/inverted-lightness-variables/',
    linkType: 'outlink',
  },
  {
    productName: '텍스트 분활 애니메이션(splitting.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://splitting.js.org/',
    linkType: 'outlink',
  },
  {
    productName: '타자치는 애니메이션(t.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://mntn-dev.github.io/t.js/',
    linkType: 'outlink',
  },
  {
    productName: '네온사인 애니메이션(novacancy.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://github.com/chuckyglitch/novacancy.js/',
    linkType: 'outlink',
  },
  {
    productName: '모자이크 애니메이션(baffle.js)',
    category: 'text-effect',
    category2: 'animation',
    url: 'https://camwiegert.github.io/baffle/',
    linkType: 'outlink',
  },
  // {
  //   productName: '',
  //   category: '',
  //   url: '',
  //   linkType: 'outlink',
  // },
]